# Generated by Django 3.1.3 on 2021-05-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('journal_reference_type', models.CharField(choices=[('DOI', 'DOI'), ('arXiv', 'arXiv')], default='DOI', max_length=64)),
                ('journal_reference_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='metrics', to='api.dataset')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.paper')),
            ],
        ),
    ]
