version: '3.3'
services:
  backend:
    container_name: paper-reg-backend
    image: paper-reg/backend:$BACKEND_IMAGE_VERSION
    build: ./backend/
    depends_on:
      - database
    environment:
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - SECRET_KEY
  database:
    image: mysql:latest
    container_name: paper-reg-mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=amacms
    volumes:
      - ./db-data:/var/lib/mysql
    ports: 
      - 3306:3306
    tty: true
  nginx:
    container_name: paper-reg-nginx
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
    depends_on:
      - backend
    restart: always
