version: '3.3'
services:
  backend:
    container_name: covidbase-backend
    image: aimedsut/covidbase-backend:$IMAGE_VERSION
    build: ./backend/
    depends_on:
      - database
    environment:
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - SECRET_KEY
      - ADMIN_USERNAME
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
  frontend:
    image: aimedsut/covidbase-frontend:$IMAGE_VERSION
    container_name: covidbase-frontend
    build: ./frontend/
    depends_on:
      - backend
    volumes:
      - frontend_vol:/mnt/frontend/
  database:
    image: mysql:latest
    container_name: covidbase-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./db-data:/var/lib/mysql
    tty: true
  nginx:
    container_name: covidbase-nginx
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
      - frontend_vol:/mnt/frontend/
    depends_on:
      - backend
      - frontend
    restart: always


volumes:
  frontend_vol:
