---
name: "Build Workflow"
env:
  DOCKER_USERNAME: aimedsut
  RELEASE_VERSION: 0.0.1 # If changed, make sure to also update this variable in deploy workflow.
  DOCKER_REPO: covidbase-backend
on:
  push:
    branches:
      - master
jobs:
  build-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/build.sh
          --service-name backend
          --version snapshot-$GITHUB_RUN_ID
          --docker-user $DOCKER_USERNAME
          --docker-pass ${{ secrets.DOCKER_PASSWORD }}
  smoke-test-backend:
    needs: build-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/smoke-test.sh
          --tag snapshot-$GITHUB_RUN_ID
          --docker-user $DOCKER_USERNAME
          --docker-pass ${{ secrets.DOCKER_PASSWORD }}
  release-backend:
    needs: smoke-test-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/release-image.sh
          --docker-repo $DOCKER_REPO
          --service-name backend
          --src-tag snapshot-$GITHUB_RUN_ID
          --release-tag $RELEASE_VERSION
          --docker-user $DOCKER_USERNAME
          --docker-pass ${{ secrets.DOCKER_PASSWORD }}
  test-deploy:
    needs: build-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
      - run: echo "TARGET_HOST=192.168.2.2" >> $GITHUB_ENV
      - run: docker network create --subnet 192.168.2.0/24 covidbase-net
      - run: docker run -d
          --network covidbase-net
          --ip $TARGET_HOST
          --privileged
          $DOCKER_USERNAME/infra-image:latest
      - run: docker run
          --network covidbase-net
          --env TARGET_HOST=$TARGET_HOST
          spy86/ansible:latest
          bash -c 'sshpass -p root ssh -o StrictHostKeyChecking=no root@$TARGET_HOST "service docker start"'
      - name: Run deploy.yml
        run: docker run
          --network covidbase-net
          -v `pwd`:/app-src/:ro
          --workdir /app-src/deploy/
          --env TARGET_HOST=$TARGET_HOST
          --env GITHUB_RUN_ID=$GITHUB_RUN_ID
          spy86/ansible:latest
          bash -c 'ansible-playbook
          -i inventory.yml
          --extra-vars="
          docker_username=$DOCKER_USERNAME
          ansible_host=$TARGET_HOST
          ansible_user=$HOST_SSH_USER
          backend_image_version=snapshot-$GITHUB_RUN_ID
          secret_key=dummy
          db_password=dummy
          mysql_root_password=dummy
          docker_hub_password=${{ secrets.DOCKER_PASSWORD }}
          admin_username=admin
          admin_email=admin@gmail.com
          admin_password=admin"
          deploy.yml'
      - name: Wait for the app to be up
        run: sleep 20
      - name: Smoke test
        run: docker run
          --network covidbase-net
          --add-host covidbase.ir:$TARGET_HOST
          -v `pwd`/.github/scripts/smoke-test.sh:/smoke-test.sh:ro
          spy86/ansible:latest
          /smoke-test.sh --host "https://covidbase.ir"

